name: tractian_challenge
description: "Challenge tractian."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  http: ^1.2.2
  mobx: ^2.4.0
  flutter_mobx: ^2.2.1+1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.14
  go_router: ^14.4.1

dev_dependencies:
  mobx_codegen: ^2.6.2
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  build_runner: ^2.4.13


flutter:
  uses-material-design: true


  assets:
    - assets/icons/
    - assets/logos/
